name: Node.js CI

on:
  push:
    branches: master
  pull_request:

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Check that the build works
        run: npm run build
